<?php
  return array(
      'albumname'=>'',
      'allowupload'=>'',
      'allowphotomanag'=>'',
      'uploadslimit'=>'0',
      'upload-from'=>'',
      'upload-to'=>'',
      'allowvotes'=>'',
      'vote-from'=>'',
      'vote-to'=>'',
      'allowselfrating'=>'',
      'hidecammodelonrate'=>'',
      'allowcomments'=>'',
      'showrateforuploads'=>'',
      'showranking'=>'',
      'watermark'=>'',
      'antitriche'=>'',
      'ratemethod'=>'',
      'RKEY'=>''
    );
?>